version: v1.1.0

dsn: postgres://auth:secret@auth-db:5432/auth?sslmode=disable&max_conns=20&max_idle_conns=4

serve:
  public:
    base_url: http://localhost:4433/
    cors:
      enabled: true
  admin:
    base_url: http://localhost:4434/

selfservice:
  default_browser_return_url: http://localhost:4455/
  allowed_return_urls:
    - http://localhost:4455

  methods:
    password:
      enabled: true
      config:
        min_password_length: 6
        identifier_similarity_check_enabled: false
        haveibeenpwned_enabled: false

  flows:
    error:
      ui_url: http://localhost:4455/error
    verification:
      enabled: true
      ui_url: http://localhost:4455/verification
      after:
        hooks:
          - hook: web_hook
            config:
              url: http://self-service-go:4455/
              method: POST # GET, DELETE, etc
              body: file:///etc/kratos/config/identity.jsonnet
    settings:
      ui_url: http://localhost:4455/settings
      privileged_session_max_age: 15m
      required_aal: highest_available
      after:
        password:
          hooks:
            # Revoke other active user sessions after changing the password
            # https://www.ory.sh/docs/kratos/session-management/revoke-sessions-hook
            # https://www.ory.sh/docs/kratos/hooks/configure-hooks
            - hook: revoke_active_sessions
    recovery:
      enabled: true
      lifespan: 15m # Defines how much time the user has to complete the recovery flow in the UI. Default: 1h.
      use: code # Defines which method is used, one of 'code' or 'link'.
      ui_url: http://localhost:4455/recovery
      notify_unknown_recipients: false # Defines if the system sends attempted recovery notifications to unregistered addresses.
    logout:
      after:
        default_browser_return_url: http://localhost:4455/login
    login:
      ui_url: http://localhost:4455/login
      after:
        password:
          hooks:
            # explanation https://www.ory.sh/docs/actions/require-verified-address
            - hook: require_verified_address
    registration:
      ui_url: http://localhost:4455/registration
# this is enabling auto login after registration
#      after:
#        password:
#          hooks:
#            - hook: session

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
  cipher:
    - 32-LONG-SECRET-NOT-SECURE-AT-ALL

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  argon2:
    parallelism: 1
    memory: 128MB
    iterations: 2
    salt_length: 16
    key_length: 16

identity:
  schemas:
    - id: default
      url: file:///etc/kratos/identity-schemas/service/json/person.schema.json
  default_schema_id: "default"

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true
